theme: minima
title: My Little Masters
author: Karoly Kemeny
description: Life went in a way that I never did an official masters in computer science, but I am a born geek and there are world-class courses since Covid, so I just put together a graduate degree worth of material. Why not?
